version: "3.9"
services:
  tomcat:
    build:
      context: .
      dockerfile: tomcat.dockerfile
    ports:
      - "8080:8080"
    volumes:
      -  ./target/webapps:/usr/local/tomcat/webapps/

  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    ports:
      - "8090:8080"
      - "50000:50000"

  #sonarqube:
  #  build:
  #    context: .
  #    dockerfile: sonarqube.dockerfile
  #  ports:
  #    - "9090:9090"
  #   - "9000:9000"